package domain

import "time"

// AIStatus represents the state of the AI enrichment pipeline for a link.
type AIStatus string

const (
	AIStatusPending    AIStatus = "pending"
	AIStatusProcessing AIStatus = "processing"
	AIStatusDone       AIStatus = "done"
	AIStatusFailed     AIStatus = "failed"
)

// Link represents a shortened URL with its associated metadata.
// It is the core domain entity of the LinkMind system.
type Link struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`       // Base62-encoded short code (e.g. "gW3k")
	LongURL   string    `json:"long_url"`   // Original full URL
	Title     string    `json:"title"`      // Title extracted by AI
	Summary   string    `json:"summary"`    // Summary generated by Gemini
	Tags      []string  `json:"tags"`       // Array of tags generated by AI
	IsActive  bool      `json:"is_active"`
	AIStatus  AIStatus  `json:"ai_status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
